### ISSUE TITLE
Add document file readme

### ISSUE THREAD

**Issue by jitendra3109** [jeremi/raphael-graph-demo#2]
In GitHub, if a Git repository has a README file in its main (top-level) directory, the README file is automatically converted into formatted HTML and presented on the main web page of the git repository, underneath the list of files and directories in the repository. Various different file extensions can be used, but there should not be more than one file named "README" at the top-level of a GitHub repository. The conversion to HTML takes account of the file extension of the file – for example, naming the README file for a GitHub repository "README.md" would cause GitHub to treat it as a GitHub-flavored Markdown file, which is also the default README file format on GitHub.
This makes using GitHub a low-effort way to create a web page for a git repository (GitHub also supports the publication of wikis and separate websites, which may be formatted however the developers want).
Because the GitHub web interface lets users edit a file in a relatively streamlined way, without manually cloning the repository and manually making a pull request, it supports wiki-style editing of the README file with approval necessary by a committer (i.e. someone who has write access to the repository) if the user is not a commit themselves.
However, within the GitHub app for Android mobile devices, the contents of README files are not shown underneath the list of files and nor are README files formatted as HTML when viewed.

**Comment by jitendra3109** [comment]
Is that anybody listen to me? I am trying to get in touch please anybody?
Actually I really like your work please just enhancement it.

**Comment by jitendra3109** [comment]
Hey, I will give you format just write rest of the content.
# Project Title

One Paragraph of project description goes here

## Getting Started

These instructions will get you a copy of the project up and run on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.

### Prerequisites

What things you need to install the software and how to install them

```
Give examples
```

### Installing

A step by step series of examples that tell you have to get a development env running

Say what the step will be

```
Give the example
```

And repeat

```
until finished
```

End with an example of getting some data out of the system or using it for a little demo

## Running the tests

Explain how to run the automated tests for this system

### Break down into end to end tests

Explain what these tests test and why

```
Give an example
```

### And coding style tests

Explain what these tests test and why

```
Give an example
```

## Deployment

Add additional notes about how to deploy this on a live system

## Built With

* [Dropwizard](http://www.dropwizard.io/1.0.2/docs/) - The web framework used
* [Maven](https://maven.apache.org/) - Dependency Management
* [ROME](https://rometools.github.io/rome/) - Used to generate RSS Feeds

## Contributing

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.

## Versioning

We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/your/project/tags). 

## Authors

* **Billie Thompson** - *Initial work* - [PurpleBooth](https://github.com/PurpleBooth)

See also the list of [contributors](https://github.com/your/project/contributors) who participated in this project.

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details

## Acknowledgments

* Hat tip to anyone who's code was used
* Inspiration
* etc

**Comment by jeremi** [comment]
This is an old project probably not working anymore.
